using System;
using System.Collections.Generic;
using System.Globalization;

namespace zavod.UI.Text;

public enum UiLanguage
{
    English,
    Russian
}

public static class UiLanguageResolver
{
    public const string EnvironmentVariable = "ZAVOD_UI_LANG";

    public static UiLanguage Resolve()
    {
        var value = Environment.GetEnvironmentVariable(EnvironmentVariable)?.Trim();
        if (string.Equals(value, "ru", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "ru-RU", StringComparison.OrdinalIgnoreCase))
        {
            return UiLanguage.Russian;
        }

        if (string.Equals(value, "en", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "en-US", StringComparison.OrdinalIgnoreCase))
        {
            return UiLanguage.English;
        }

        var culture = CultureInfo.CurrentUICulture;
        if (string.IsNullOrWhiteSpace(culture.Name))
        {
            culture = CultureInfo.CurrentCulture;
        }

        return string.Equals(culture.TwoLetterISOLanguageName, "ru", StringComparison.OrdinalIgnoreCase)
            ? UiLanguage.Russian
            : UiLanguage.English;
    }
}

public static class AppText
{
    private static UiTextCatalog _current = UiTextCatalog.English;

    public static UiTextCatalog Current => _current;

    public static UiLanguage CurrentLanguage { get; private set; } = UiLanguage.English;

    public static void Use(UiLanguage language)
    {
        CurrentLanguage = language;
        _current = language == UiLanguage.Russian
            ? UiTextCatalog.Russian
            : UiTextCatalog.English;
    }
}

public sealed class UiTextCatalog
{
    private readonly IReadOnlyDictionary<string, string> _texts;

    private UiTextCatalog(UiLanguage language, IReadOnlyDictionary<string, string> texts)
    {
        Language = language;
        _texts = texts;
    }

    public UiLanguage Language { get; }

    public string LanguageCode => Language == UiLanguage.Russian ? "ru" : "en";

    public string Get(string key)
    {
        if (_texts.TryGetValue(key, out var value))
        {
            return value;
        }

        throw new KeyNotFoundException($"Missing UI text key '{key}' for language '{LanguageCode}'.");
    }

    public string Format(string key, params object?[] args)
    {
        return string.Format(CultureInfo.InvariantCulture, Get(key), args);
    }

    public static UiTextCatalog English { get; } = new(UiLanguage.English, new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["shell.back"] = "Back",
        ["shell.refresh"] = "Refresh",
        ["shell.recovery_mode_active"] = "Recovery mode active.",
        ["shell.first_frame_ready"] = "Shell test bed active. Chats web renderer mounted under the clean shell.",
        ["shell.shell_pass_active"] = "Shell test bed active. Chats web renderer under clean shell. Minimum size {0}x{1}.",
        ["shell.chats_mode_active"] = "Chats mode active. Free chat stays outside project lifecycle.",
        ["shell.projects_mode_active"] = "Projects mode active. List, Home, and Work Cycle hosts are restored; discussion/preflight path is partially reconnected.",
        ["shell.projects_mode_demo_active"] = "Projects mode active. Demo runtime detected. List, Home, and Work Cycle hosts are restored; discussion/preflight path is partially reconnected.",
        ["mode.chats"] = "Chats",
        ["mode.projects"] = "Projects",
        ["role.user"] = "User",
        ["role.assistant"] = "Assistant",
        ["role.worker"] = "Worker",
        ["role.shift_lead"] = "Shift Lead",
        ["role.qc"] = "QC",
        ["role.system"] = "System",
        ["conversation.default_log_label"] = "Log",
        ["conversation.default_artifact_label"] = "Artifact",
        ["conversation.execution_brief_label"] = "Execution brief",
        ["conversation.reference_separator"] = " • ",
        ["conversation.preview.file"] = "File attached and ready as an artifact.",
        ["conversation.preview.document"] = "Document attached and ready as an artifact.",
        ["conversation.preview.image"] = "Image attached and ready as an artifact.",
        ["conversation.preview.archive"] = "Archive attached and ready as an artifact.",
        ["conversation.preview.pdf"] = "PDF attached and ready as an artifact.",
        ["chats.empty.headline"] = "Quiet space for a thought",
        ["chats.empty.subtitle"] = "Start anywhere. Structure can arrive later.",
        ["chats.composer.placeholder"] = "Start a thought...",
        ["chats.draft.title"] = "New chat",
        ["chats.current.title"] = "Current chat",
        ["chats.sidebar.show"] = "Show chat list",
        ["chats.sidebar.hide"] = "Hide chat list",
        ["chats.new_chat"] = "New chat",
        ["chats.add_attachment.title"] = "Add",
        ["chats.send.title"] = "Send",
        ["chats.add_file"] = "File",
        ["chats.add_image"] = "Image",
        ["chats.add_note"] = "Note",
        ["chats.load_older"] = "Load older",
        ["chats.loading_older"] = "Loading...",
        ["chats.openrouter.failed"] = "OpenRouter request failed: {0}. {1}",
        ["chats.openrouter.empty_failed"] = "OpenRouter request failed: empty response.",
        ["projects.host.title"] = "Projects",
        ["projects.empty.headline"] = "{0}: no conversation yet",
        ["projects.empty.subtitle"] = "Project imported. Its memory is still preview-only; review, promote, or start a thin-memory first task.",
        ["projects.empty.status"] = "{0}/5 canonical · {1}/5 preview · preview-only",
        ["projects.empty.missing_truth"] = "Missing canonical truth:",
        ["projects.warning.container_root_selection_required"] = "This import is a project container; select/import a specific child root before promotion or execution.",
        ["projects.draft.title"] = "New project conversation",
        ["projects.screen.list.title"] = "Project List",
        ["projects.screen.list.summary"] = "Project List host is restored as the non-mutating entry layer for Projects.",
        ["projects.screen.home.title"] = "Project Home",
        ["projects.screen.home.summary"] = "Project Home host is restored as a simple read-only overview layer.",
        ["projects.screen.work_cycle.title"] = "Project Work Cycle",
        ["projects.screen.work_cycle.summary"] = "Project Work Cycle host is restored; discussion and preflight semantics are partially reconnected on the proven owner path.",
        ["projects.token.none"] = "none",
        ["projects.token.missing"] = "missing",
        ["projects.shell.entry_state"] = "Project entry: {0}",
        ["projects.shell.storage_initialized"] = ".zavod initialized at {0}",
        ["projects.shell.storage_missing"] = ".zavod storage root is missing",
        ["projects.shell.active_shift"] = "Active shift: {0}",
        ["projects.shell.active_task"] = "Active task: {0}",
        ["projects.shell.no_project_document"] = "No project document is currently materialized.",
        ["projects.shell.current_stage"] = "Current stage: {0}. Import kind: {1}.",
        ["projects.shell.health"] = "Health: {0}. Import kind: {1}.",
        ["projects.shell.home_stage"] = "Document stage: {0}. project doc={1}, capsule={2}.",
        ["projects.shell.home_activity"] = "Active shift: {0}. Active task: {1}.",
        ["projects.shell.document_state"] = "Document state: {0}, {1}",
        ["projects.shell.materials_empty"] = "No user-facing materials were detected by the scanner yet.",
        ["projects.enum.import.empty"] = "Empty",
        ["projects.enum.import.source_project"] = "Source Project",
        ["projects.enum.import.non_source"] = "Non-Source Import",
        ["projects.enum.import.mixed"] = "Mixed Import",
        ["projects.enum.entry_mode.bootstrap"] = "Начальная инициализация",
        ["projects.enum.entry_mode.resume"] = "Продолжение",
        ["projects.enum.health.healthy"] = "Healthy",
        ["projects.enum.health.missing"] = "Missing",
        ["projects.enum.health.unavailable"] = "Unavailable",
        ["projects.enum.health.broken_structure"] = "Broken Structure",
        ["projects.enum.health.material_only"] = "Material Only",
        ["projects.enum.health.degraded"] = "Degraded",
        ["projects.enum.health.scan_pending"] = "Scan Pending",
        ["projects.enum.health.scan_failed"] = "Scan Failed",
        ["projects.enum.document_stage.import_preview"] = "Import Preview",
        ["projects.enum.document_stage.preview_docs"] = "Preview Docs",
        ["projects.enum.document_stage.canonical_docs"] = "Canonical Docs",
        ["projects.enum.material.text_document"] = "Text Document",
        ["projects.enum.material.pdf_document"] = "PDF Document",
        ["projects.enum.material.office_document"] = "Office Document",
        ["projects.enum.material.spreadsheet"] = "Spreadsheet",
        ["projects.enum.material.presentation"] = "Presentation",
        ["projects.enum.material.image_asset"] = "Image Asset",
        ["projects.enum.material.archive_artifact"] = "Archive Artifact",
        ["projects.enum.material.multimedia"] = "Multimedia",
        ["projects.recovery.execution_state.recovery_hold"] = "Recovery hold",
        ["projects.recovery.execution_state.task_detected"] = "Task context detected",
        ["projects.recovery.execution_detail.disabled"] = "Execution wiring is still disabled. The center surface is back only as a verified shell.",
        ["projects.recovery.execution_detail.task_detected"] = "{0} but execution controls remain intentionally disconnected during recovery.",
        ["projects.recovery.result_state.evidence_available"] = "Evidence available",
        ["projects.recovery.result_state.none"] = "No result loaded",
        ["projects.recovery.result_detail.capsule_exists"] = "A capsule document exists and can be opened from the execution surface.",
        ["projects.recovery.result_detail.none"] = "No capsule/result document is materialized yet.",
        ["projects.list.title"] = "Project List",
        ["projects.list.start_here.title"] = "Start Here",
        ["projects.list.start_here.body"] = "Projects mode starts here. Import and New Project remain explicit entry actions.",
        ["projects.list.start_here.new_project"] = "New project",
        ["projects.list.start_here.import"] = "Import",
        ["projects.list.current_project.title"] = "Current Project",
        ["projects.list.current_project.open"] = "Open project",
        ["projects.list.summary"] = "Choose a project entry block. Import and New Project stay disconnected in this slice.",
        ["projects.list.current_project.details"] = "Current project entry remains read-only in this slice.",
        ["projects.list.notes"] = "This list stays read-only for now.",
        ["projects.home.title"] = "Project Home",
        ["projects.home.open_html"] = "Open HTML",
        ["projects.home.open_project_doc"] = "Open project doc",
        ["projects.home.open_work_cycle"] = "Open work cycle",
        ["projects.home.overview"] = "Overview",
        ["projects.home.materials"] = "Materials",
        ["projects.home.summary"] = "Open HTML, inspect materials, and read a few truthful status lines.",
        ["projects.home.notes"] = "This surface stays read-only in the current slice.",
        ["projects.work_cycle.chat.title"] = "Chat",
        ["projects.work_cycle.focus.auto"] = "Auto",
        ["projects.work_cycle.focus.chat"] = "Chat",
        ["projects.work_cycle.focus.execution"] = "Execution",
        ["projects.work_cycle.focus.result"] = "Result",
        ["projects.work_cycle.project.title"] = "Project",
        ["projects.work_cycle.project.root"] = "Project root",
        ["projects.work_cycle.state.title"] = "State",
        ["projects.work_cycle.enter_work"] = "Enter work",
        ["projects.work_cycle.composer.placeholder"] = "Describe the task or add clarification",
        ["projects.work_cycle.composer.send"] = "Send",
        ["projects.work_cycle.execution.title"] = "Execution Surface",
        ["projects.work_cycle.execution.state"] = "Execution state",
        ["projects.work_cycle.validation.title"] = "Validation",
        ["projects.work_cycle.available_evidence"] = "Available evidence",
        ["projects.work_cycle.execution.confirm"] = "Confirm",
        ["projects.work_cycle.execution.clarify"] = "Clarify",
        ["projects.work_cycle.execution.return_to_chat"] = "Return to chat",
        ["projects.work_cycle.execution.clarification_placeholder"] = "Describe what must be clarified",
        ["projects.work_cycle.execution.apply_clarification"] = "Apply clarification",
        ["projects.work_cycle.execution.cancel_clarification"] = "Cancel",
        ["projects.work_cycle.open_project_doc"] = "Open project doc",
        ["projects.work_cycle.open_capsule_doc"] = "Open capsule doc",
        ["projects.work_cycle.execution.confirm_stub"] = "Confirm",
        ["projects.work_cycle.execution.clarify_stub"] = "Clarify",
        ["projects.work_cycle.execution.cancel_stub"] = "Pause/Cancel",
        ["projects.work_cycle.result.title"] = "Result Surface",
        ["projects.work_cycle.result.state"] = "Result state",
        ["projects.work_cycle.result.accept"] = "Accept",
        ["projects.work_cycle.result.revise"] = "Revise",
        ["projects.work_cycle.result.reject"] = "Reject",
        ["projects.work_cycle.result.withheld"] = "What was intentionally withheld",
        ["projects.work_cycle.result.return_to_execution"] = "Return to execution",
        ["projects.work_cycle.phase_prefix"] = "Phase: ",
        ["projects.work_cycle.chat.summary_note_active"] = "Discussion UI is active only in discussion-like phases. Core-driven actions remain limited to proven owner paths.",
        ["projects.work_cycle.validation.reason"] = "Validation of the agreement before execution start.",
        ["projects.work_cycle.validation.empty"] = "Agreement has not been formed yet.",
        ["projects.chrome.note.discussion"] = "Discussion is active in this phase. Send stays discussion-only, and work entry remains a separate validated transition.",
        ["projects.chrome.note.execution_preflight"] = "Chat stays primary while the same persistent execution surface opens in validation/preflight mode.",
        ["projects.chrome.note.execution"] = "Execution is the active surface. Chat remains visible only as bounded frozen context in this slice.",
        ["projects.chrome.note.result"] = "Result is the active decision surface. Execution stays visible as context and chat remains frozen.",
        ["projects.chrome.note.completed"] = "Completed state is shown as historical context only in this slice.",
        ["projects.chrome.note.fallback"] = "Discussion and execution stay limited to the currently re-proven owner paths.",
        ["projects.work_cycle.summary"] = "Current phase: {0}. Work Cycle follows phase-driven visibility, and the discussion/preflight owner path is partially reconnected.",
        ["projects.work_cycle.phase.discussion_reopened"] = "Discussion / Reopened",
        ["projects.work_cycle.phase.discussion_ready"] = "Discussion / Ready",
        ["projects.work_cycle.phase.discussion_forming"] = "Discussion / Forming",
        ["projects.work_cycle.phase.execution_preflight"] = "Execution / Preflight",
        ["projects.work_cycle.phase.execution_running"] = "Execution / Running",
        ["projects.work_cycle.phase.execution_qc"] = "Execution / QC",
        ["projects.work_cycle.phase.execution_revision"] = "Execution / Revision",
        ["projects.work_cycle.phase.execution_interrupted"] = "Execution / Interrupted",
        ["projects.work_cycle.phase.result_revision_requested"] = "Result / Revision Requested",
        ["projects.work_cycle.phase.result_ready"] = "Result / Ready",
        ["projects.work_cycle.phase.completed"] = "Completed",
        ["projects.work_cycle.phase.discussion_idle"] = "Discussion / Idle",
        ["projects.work_cycle.chat_title.discussion"] = "Discussion",
        ["projects.work_cycle.chat_title.execution"] = "Frozen Context",
        ["projects.work_cycle.chat_title.result"] = "Decision Context",
        ["projects.work_cycle.chat_title.completed"] = "Completed Context",
        ["projects.work_cycle.surface.primary"] = "Primary surface",
        ["projects.work_cycle.surface.frozen"] = "Frozen context",
        ["projects.work_cycle.surface.historical"] = "Historical context",
        ["projects.work_cycle.surface.context"] = "Context",
        ["projects.work_cycle.surface.hidden"] = "Hidden",
        ["projects.work_cycle.surface.active"] = "Active surface",
        ["projects.work_cycle.surface.reference"] = "Reference surface",
        ["projects.work_cycle.surface.visible"] = "Visible surface",
        ["projects.work_cycle.chat_summary.discussion"] = "Chat is the primary surface in this phase. It frames intent and keeps the project discussion visible without creating work truth on its own.",
        ["projects.work_cycle.chat_summary.execution"] = "Chat remains visible only as bounded context while execution becomes the active work surface.",
        ["projects.work_cycle.chat_summary.result"] = "Chat stays visible as frozen context while execution/result carry the active work and decision surfaces.",
        ["projects.work_cycle.chat_summary.completed"] = "The visible discussion context is now historical and no longer an active control surface.",
        ["projects.work_cycle.chat_summary.fallback"] = "Chat remains part of the current project context.",
        ["projects.work_cycle.chat_summary_note.discussion"] = "Composer and agreement actions remain disconnected in this slice.",
        ["projects.work_cycle.chat_summary_note.execution"] = "Execution phase must not reintroduce free-form discussion UI as active control.",
        ["projects.work_cycle.chat_summary_note.result"] = "Result visibility must not imply lifecycle completion.",
        ["projects.work_cycle.chat_summary_note.completed"] = "Completed state must not silently erase step history.",
        ["projects.work_cycle.execution_summary.hidden"] = "Execution surface is hidden until the phase engine reaches execution/result territory.",
        ["projects.work_cycle.execution_summary.preflight"] = "Execution is present as a prepared shell before active work begins.",
        ["projects.work_cycle.execution_summary.running"] = "Execution is the active work surface in this phase.",
        ["projects.work_cycle.execution_summary.qc"] = "Execution remains visible while QC-related state is active.",
        ["projects.work_cycle.execution_summary.revision"] = "Execution is active again because the current task is in revision flow.",
        ["projects.work_cycle.execution_summary.interrupted"] = "Execution stays visible as an interrupted/degraded work surface.",
        ["projects.work_cycle.execution_summary.visible"] = "Execution surface is visible because the current phase requires it.",
        ["projects.work_cycle.execution_detail.preflight"] = "Preflight must not create active work truth on its own. It stays read-only in this slice.",
        ["projects.work_cycle.execution_detail.running"] = "Task context: {0}. Live controls remain disconnected.",
        ["projects.work_cycle.execution_detail.qc"] = "QC-adjacent execution context remains projection-only. {0}",
        ["projects.work_cycle.execution_detail.revision"] = "Revision-capable execution context is visible. {0}",
        ["projects.work_cycle.execution_detail.interrupted"] = "Interrupted execution must degrade honestly and must not pretend live running survived restart.",
        ["projects.work_cycle.execution_detail.fallback"] = "Execution details remain read-only until owner paths are re-proven.",
        ["projects.work_cycle.execution_evidence.result_visible"] = "Execution remains visible beside Result.",
        ["projects.work_cycle.execution_evidence.context"] = "Execution evidence remains available as context.",
        ["projects.work_cycle.execution_evidence.format"] = "Document state: project={0}, capsule={1}. {2}",
        ["projects.work_cycle.result_summary.hidden"] = "Result surface stays hidden until the phase engine reaches result/revision territory.",
        ["projects.work_cycle.result_summary.ready"] = "Result is now the active decision surface while execution remains visible as context.",
        ["projects.work_cycle.result_summary.revision"] = "Result remains visible as reference because the current task is in revision flow.",
        ["projects.work_cycle.result_summary.visible"] = "Result surface is visible because the current phase requires it.",
        ["projects.work_cycle.result_surface.active"] = "Active decision surface",
        ["projects.work_cycle.result_surface.reference"] = "Reference decision surface",
        ["projects.work_cycle.result_surface.visible"] = "Visible decision surface",
        ["projects.work_cycle.result_detail.ready"] = "Result remains read-only in this slice. {0}",
        ["projects.work_cycle.result_detail.revision"] = "Revision keeps the result visible, but decision hooks remain disconnected in this slice.",
        ["projects.work_cycle.result_detail.fallback"] = "Result details remain read-only until owner paths are re-proven.",
        ["projects.work_cycle.result_evidence.capsule_present"] = "Capsule/result evidence is present.",
        ["projects.work_cycle.result_evidence.capsule_missing"] = "Capsule/result evidence is not materialized yet.",
        ["projects.work_cycle.result_evidence.revision_reference"] = "Result remains on screen as revision reference.",
        ["projects.work_cycle.result_evidence.decision_surface"] = "Result stays a decision surface only when supported by phase truth.",
        ["projects.work_cycle.result_metadata.revision"] = "Revision reference active.",
        ["projects.work_cycle.result_metadata.ready"] = "Decision review active.",
        ["projects.work_cycle.result_metadata.unavailable"] = "Decision review unavailable.",
        ["projects.work_cycle.result_metadata.format"] = "Document stage: {0}. {1}",
        ["projects.message.default_revision_reason"] = "Revision requested from result surface.",
        ["projects.message.revision_input_received"] = "Revision input received. Worker produced a new result.",
        ["projects.message.revision_log_prepared"] = "Revision log prepared from the typed execution runtime.",
        ["projects.message.revision_execution_brief_prepared"] = "Revised execution brief prepared from the typed execution runtime.",
        ["projects.message.revision_accepted"] = "QC accepted the revised result. Result surface is ready again.",
        ["projects.message.agreement_ready"] = "Agreement looks strong enough to move into preflight validation.",
        ["projects.message.agreement_ready_with_defaults"] = "Got it. I will frame this as a bounded first pass using observed project evidence and safe defaults; unknown toolchain or asset details stay as warnings for execution review.",
        ["projects.message.agreement_refining"] = "Keep refining the request until the work can be validated without guesswork.",
        ["projects.message.agreement_continue"] = "Continue clarifying the request before starting work.",
        ["projects.message.preflight_opened"] = "Preflight opened. Validation stays active before execution starts.",
        ["projects.message.preflight_confirmed"] = "Preflight confirmed. Execution runtime started.",
        ["projects.message.execution_guard"] = "Execution guard: {0}",
        ["projects.message.worker_working"] = "Working...",
        ["projects.message.worker_log_prepared"] = "Worker log prepared from the typed execution runtime.",
        ["projects.message.execution_brief_prepared"] = "Execution brief prepared from the typed execution runtime.",
        ["projects.message.qc_accepted_produced_result"] = "QC accepted the produced result. Result surface is ready for decision.",
        ["projects.message.run_profile_completed"] = "Build/run profile command completed. Result surface is ready for review.",
        ["projects.message.run_profile_failed_revision"] = "Build/run profile command failed or timed out. Revision is open with process output.",
        ["projects.message.execution_runtime_failed"] = "Execution runtime failed before producing a result: {0}. {1}",
        ["projects.message.qc_decision_accept"] = "QC decision: ACCEPT. {0}",
        ["projects.message.qc_decision_revise"] = "QC decision: REVISE. {0}",
        ["projects.message.qc_decision_reject"] = "QC decision: REJECT. {0}",
        ["projects.message.qc_decision_unavailable"] = "QC agent unavailable ({0}). Result was not accepted; execution returned for revision or retry.",
        ["projects.message.worker_refused_abandoned"] = "Worker returned refused/failed. No reviewable result produced; task {0} abandoned without QC review.",
        ["projects.message.qc_revise_revision_cycle_opened"] = "QC decision was REVISE. Execution returned to revision cycle; provide the revision intake to continue.",
        ["projects.message.qc_reject_task_abandoned"] = "QC decision was REJECT. Task {0} abandoned; shift stays open.",
        ["projects.message.staged_summary"] = "Worker staged {0} file(s) to the sandbox ({1} applied, {2} skipped). Staging root: {3}",
        ["projects.message.staging_applied"] = "Applied {0} staged file(s) to the project: {1}",
        ["projects.message.staging_hash_drift"] = "Hash drift detected during apply: {0}",
        ["projects.message.accepted_result_apply_blocked"] = "Accepted result apply blocked: {0}",
        ["projects.message.worker_llm_unavailable_fresh"] = "Worker LLM was unavailable ({0}). Task {1} marked abandoned; staging preserved for inspection. Send the intent again to retry.",
        ["projects.message.worker_llm_unavailable_revision"] = "Worker LLM was unavailable ({0}). Revision cycle kept intact; staging preserved. Send your revision text again to retry.",
        ["projects.message.clarification_requested"] = "Clarification requested before execution start.",
        ["projects.message.clarification_accepted"] = "Clarification accepted. Updated agreement: {0}",
        ["projects.message.returned_to_chat"] = "Returned to chat. Execution runtime was not started.",
        ["projects.message.interrupted_returned_to_chat"] = "Returned to chat from interrupted execution. No result was applied.",
        ["projects.message.accepted_result_applied"] = "Accepted result applied. Commit recorded as {0}.",
        ["projects.message.revision_requested"] = "Revision requested. Execution returned to revision cycle.",
        ["projects.message.result_rejected"] = "Result rejected. Task {0} was abandoned and the shift stays open.",
        ["projects.message.agreement_not_formed"] = "- Agreement has not been formed yet.",
        ["projects.message.recovered_task_from_validation"] = "Recovered task from UI validation.",
        ["projects.message.acceptance.project"] = "Produce evidence-backed output for project '{0}'.",
        ["projects.message.acceptance.qc"] = "QC decision must happen before apply or reject.",
        ["projects.message.acceptance.document_stage"] = "Respect current document stage '{0}'.",
        ["projects.message.worker_artifact.heading"] = "# Execution Brief",
        ["projects.message.worker_artifact.project"] = "Project: {0}",
        ["projects.message.worker_artifact.root"] = "Root: {0}",
        ["projects.message.worker_artifact.task"] = "Task: {0}",
        ["projects.message.worker_artifact.task_description"] = "Task Description: {0}",
        ["projects.message.worker_artifact.runtime_state"] = "Runtime State: {0}",
        ["projects.message.worker_artifact.qc_status"] = "QC Status: {0}",
        ["projects.message.worker_artifact.result"] = "## Result",
        ["projects.message.worker_artifact.advisory"] = "## Advisory",
        // ── Projects Web UI (prototype, EN) ────────────────────────────────
        ["projects.title"] = "ZAVOD · Projects",
        ["projects.phase.list"] = "list",
        ["projects.phase.home"] = "home",
        ["projects.phase.workCycle"] = "work cycle",
        ["projects.list.import"] = "Import project",
        ["projects.list.new"] = "New project",
        ["projects.status.active"] = "active",
        ["projects.status.review"] = "review",
        ["projects.status.idle"] = "idle",
        ["projects.nav.toList"] = "projects",
        ["projects.nav.toHome"] = "home",
        ["projects.stats.files"] = "files",
        ["projects.stats.anchors"] = "facts found",
        ["projects.stats.tasks"] = "tasks",
        ["projects.stats.docs"] = "documents",
        ["projects.home.currentLabel"] = "current project",
        ["projects.home.enterWork"] = "enter work cycle",
        ["projects.home.scannerAnalysis"] = "scanner analysis",
        ["projects.home.truthDocs"] = "truth documents",
        ["projects.home.nextActions"] = "next actions",
        ["projects.home.missingTruth"] = "missing truth",
        ["projects.home.userDocs"] = "user documents",
        ["projects.welcome.action.review_preview_docs"] = "review previews",
        ["projects.welcome.action.promote_preview_to_canonical"] = "promote truth docs",
        ["projects.welcome.action.author_canonical_doc"] = "author missing doc",
        ["projects.welcome.action.start_work_cycle"] = "start work cycle",
        ["projects.welcome.action.continue_work_cycle"] = "continue work",
        ["projects.welcome.action.review_project_audit"] = "review audit",
        ["projects.welcome.action.review_stale_sections"] = "review stale sections",
        ["projects.welcome.action.import_retry"] = "retry import",
        ["projects.welcome.action.reject_preview"] = "reject preview",
        ["projects.welcome.action.open_roadmap"] = "open roadmap",
        ["projects.welcome.action.open_direction"] = "open direction",
        ["projects.welcome.detail.review_preview_docs"] = "Open the preview document block and inspect candidate truth.",
        ["projects.welcome.detail.promote_preview_to_canonical"] = "Use per-document promote buttons for reviewed preview files.",
        ["projects.welcome.detail.author_canonical_doc"] = "Manual authoring flow is not wired in this build.",
        ["projects.welcome.detail.start_work_cycle"] = "Open the work cycle surface and describe the first task.",
        ["projects.welcome.detail.continue_work_cycle"] = "Return to the active project work surface.",
        ["projects.welcome.detail.review_project_audit"] = "Open scanner evidence and imported project audit.",
        ["projects.welcome.detail.review_stale_sections"] = "Stale-section review is not wired in this build.",
        ["projects.welcome.detail.import_retry"] = "Run project import again for this workspace.",
        ["projects.welcome.detail.reject_preview"] = "Use per-document reject buttons for preview files.",
        ["projects.welcome.detail.open_roadmap"] = "Roadmap surface is not wired in this build.",
        ["projects.welcome.detail.open_direction"] = "Direction surface is not wired in this build.",
        ["projects.report.label"] = "scanner report",
        ["projects.report.open"] = "open",
        ["projects.report.modal.label"] = "scanner report",
        ["projects.report.modal.close"] = "close ✕",
        ["projects.anchor.tag.file"] = "file",
        ["projects.anchor.tag.problem"] = "problem",
        ["projects.anchor.tag.dependency"] = "dependency",
        ["projects.anchor.conf.confirmed"] = "confirmed",
        ["projects.anchor.conf.likely"] = "likely",
        ["projects.docs.category.text"] = "markdown · txt",
        ["projects.docs.category.pdf"] = "pdf",
        ["projects.docs.category.html"] = "html",
        ["projects.docs.promote"] = "promote",
        ["projects.docs.reject"] = "reject",
        ["projects.docs.canonical"] = "canonical",
        ["projects.docs.absent"] = "absent",
        ["projects.composer.placeholder"] = "Describe the task...",
        ["projects.composer.intent"] = "to work",
        ["projects.composer.intent.kbd"] = "tab",
        ["projects.preflight.kicker"] = "Execution plan",
        ["projects.preflight.title"] = "Preflight",
        ["projects.preflight.confirm"] = "Run",
        ["projects.preflight.clarify"] = "Clarify",
        ["projects.preflight.back"] = "Back",
        ["projects.preflight.clarify.label"] = "clarification",
        ["projects.preflight.clarify.placeholder"] = "what should be corrected...",
        ["projects.preflight.clarify.send"] = "send ↑",
        ["projects.worker.label"] = "worker",
        ["projects.artifact.code"] = "code",
        ["projects.artifact.preview"] = "preview",
        ["projects.artifact.waiting"] = "waiting for changes...",
        ["projects.artifact.refresh"] = "refresh",
        ["projects.artifact.share"] = "share",
        ["projects.action.tasks"] = "tasks",
        ["projects.action.files"] = "files",
        ["projects.action.errors"] = "errors",
        ["projects.action.revise.placeholder"] = "what to revise...",
        ["projects.action.revise.send"] = "send ↑",
        ["projects.action.revise"] = "Revise",
        ["projects.action.reject"] = "Reject",
        ["projects.action.confirm"] = "Confirm",
        // ── New project modal (EN) ────────────────────────────────────────
        ["projects.newProject.title"] = "New project",
        ["projects.newProject.nameLabel"] = "Name",
        ["projects.newProject.namePlaceholder"] = "My new project",
        ["projects.newProject.kindLabel"] = "What is it (rough hint)",
        ["projects.newProject.pathLabel"] = "Will be created in",
        ["projects.newProject.pathHint"] = "Folder name is fixed at create time. Project name stays editable.",
        ["projects.newProject.cancel"] = "Cancel",
        ["projects.newProject.create"] = "Create",
        ["projects.kind.generic"] = "Other",
        ["projects.kind.webFrontend"] = "Web app (frontend)",
        ["projects.kind.webBackend"] = "Backend service",
        ["projects.kind.game"] = "Game",
        ["projects.kind.library"] = "Library / SDK",
        ["projects.kind.mobile"] = "Mobile app",
        ["projects.kind.cli"] = "CLI tool",
        ["projects.kind.docs"] = "Documentation"
    });

    public static UiTextCatalog Russian { get; } = new(UiLanguage.Russian, new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["shell.back"] = "Назад",
        ["shell.refresh"] = "Обновить",
        ["shell.recovery_mode_active"] = "Активен режим восстановления.",
        ["shell.first_frame_ready"] = "Тестовый shell активен. Веб-рендерер чатов смонтирован в чистом shell.",
        ["shell.shell_pass_active"] = "Тестовый shell активен. Веб-рендерер чатов работает в чистом shell. Минимальный размер {0}x{1}.",
        ["shell.chats_mode_active"] = "Активен режим чатов. Свободный чат живет вне проектного цикла.",
        ["shell.projects_mode_active"] = "Активен режим проектов. Хосты List, Home и Work Cycle восстановлены; путь discussion/preflight частично подключен.",
        ["shell.projects_mode_demo_active"] = "Активен режим проектов. Обнаружен demo runtime. Хосты List, Home и Work Cycle восстановлены; путь discussion/preflight частично подключен.",
        ["mode.chats"] = "Чаты",
        ["mode.projects"] = "Проекты",
        ["role.user"] = "Пользователь",
        ["role.assistant"] = "Ассистент",
        ["role.worker"] = "Исполнитель",
        ["role.shift_lead"] = "Лид смены",
        ["role.qc"] = "QC",
        ["role.system"] = "SYSTEM",
        ["conversation.default_log_label"] = "Лог",
        ["conversation.default_artifact_label"] = "Артефакт",
        ["conversation.execution_brief_label"] = "Краткий отчет по исполнению",
        ["conversation.reference_separator"] = " • ",
        ["conversation.preview.file"] = "Файл прикреплен и готов как артефакт.",
        ["conversation.preview.document"] = "Документ прикреплен и готов как артефакт.",
        ["conversation.preview.image"] = "Изображение прикреплено и готово как артефакт.",
        ["conversation.preview.archive"] = "Архив прикреплен и готов как артефакт.",
        ["conversation.preview.pdf"] = "PDF прикреплен и готов как артефакт.",
        ["chats.empty.headline"] = "Тихое пространство для мысли",
        ["chats.empty.subtitle"] = "Начните с любого места. Структура появится позже.",
        ["chats.composer.placeholder"] = "Начни мысль...",
        ["chats.draft.title"] = "Новый чат",
        ["chats.current.title"] = "Текущий чат",
        ["chats.sidebar.show"] = "Показать список чатов",
        ["chats.sidebar.hide"] = "Скрыть список чатов",
        ["chats.new_chat"] = "Новый чат",
        ["chats.add_attachment.title"] = "Добавить",
        ["chats.send.title"] = "Отправить",
        ["chats.add_file"] = "Файл",
        ["chats.add_image"] = "Изображение",
        ["chats.add_note"] = "Заметка",
        ["chats.load_older"] = "Загрузить более ранние",
        ["chats.loading_older"] = "Загрузка...",
        ["chats.openrouter.failed"] = "Запрос OpenRouter завершился ошибкой: {0}. {1}",
        ["chats.openrouter.empty_failed"] = "Запрос OpenRouter завершился ошибкой: пустой ответ.",
        ["projects.host.title"] = "Проекты",
        ["projects.empty.headline"] = "{0}: работа ещё не начата",
        ["projects.empty.subtitle"] = "Проект импортирован. Память пока preview-only; можно проверить документы, принять их в канон или начать первую задачу с тонким контекстом.",
        ["projects.empty.status"] = "{0}/5 canonical · {1}/5 preview · preview-only",
        ["projects.empty.missing_truth"] = "Не хватает канонической правды:",
        ["projects.warning.container_root_selection_required"] = "Это импорт папки-контейнера; выберите или импортируйте конкретный дочерний проект перед принятием в канон или работой.",
        ["projects.draft.title"] = "Новая беседа проекта",
        ["projects.screen.list.title"] = "Список проектов",
        ["projects.screen.list.summary"] = "Хост списка проектов восстановлен как немутирующий входной слой для Projects.",
        ["projects.screen.home.title"] = "Главная проекта",
        ["projects.screen.home.summary"] = "Хост главной проекта восстановлен как простой обзорный слой только для чтения.",
        ["projects.screen.work_cycle.title"] = "Рабочий цикл проекта",
        ["projects.screen.work_cycle.summary"] = "Хост рабочего цикла проекта восстановлен; semantics discussion/preflight частично подключены по подтвержденному owner path.",
        ["projects.token.none"] = "нет",
        ["projects.token.missing"] = "отсутствует",
        ["projects.shell.entry_state"] = "Вход проекта: {0}",
        ["projects.shell.storage_initialized"] = ".zavod инициализирован в {0}",
        ["projects.shell.storage_missing"] = "Корень хранения .zavod отсутствует",
        ["projects.shell.active_shift"] = "Активная смена: {0}",
        ["projects.shell.active_task"] = "Активная задача: {0}",
        ["projects.shell.no_project_document"] = "Документ проекта пока не материализован.",
        ["projects.shell.current_stage"] = "Текущая стадия: {0}. Вид импорта: {1}.",
        ["projects.shell.health"] = "Состояние: {0}. Вид импорта: {1}.",
        ["projects.shell.home_stage"] = "Стадия документа: {0}. проект={1}, capsule={2}.",
        ["projects.shell.home_activity"] = "Активная смена: {0}. Активная задача: {1}.",
        ["projects.shell.document_state"] = "Состояние документов: {0}, {1}",
        ["projects.shell.materials_empty"] = "Сканер пока не обнаружил пользовательских материалов.",
        ["projects.enum.import.empty"] = "Пусто",
        ["projects.enum.import.source_project"] = "Исходный проект",
        ["projects.enum.import.non_source"] = "Импорт без исходников",
        ["projects.enum.import.mixed"] = "Смешанный импорт",
        ["projects.enum.entry_mode.bootstrap"] = "Bootstrap",
        ["projects.enum.entry_mode.resume"] = "Resume",
        ["projects.enum.health.healthy"] = "Нормально",
        ["projects.enum.health.missing"] = "Отсутствует",
        ["projects.enum.health.unavailable"] = "Недоступно",
        ["projects.enum.health.broken_structure"] = "Структура нарушена",
        ["projects.enum.health.material_only"] = "Material Only",
        ["projects.enum.health.degraded"] = "Degraded",
        ["projects.enum.health.scan_pending"] = "Сканирование ожидается",
        ["projects.enum.health.scan_failed"] = "Сканирование завершилось ошибкой",
        ["projects.enum.document_stage.import_preview"] = "Предпросмотр импорта",
        ["projects.enum.document_stage.preview_docs"] = "Документы предпросмотра",
        ["projects.enum.document_stage.canonical_docs"] = "Канонические документы",
        ["projects.enum.material.text_document"] = "Текстовый документ",
        ["projects.enum.material.pdf_document"] = "PDF-документ",
        ["projects.enum.material.office_document"] = "Офисный документ",
        ["projects.enum.material.spreadsheet"] = "Таблица",
        ["projects.enum.material.presentation"] = "Презентация",
        ["projects.enum.material.image_asset"] = "Изображение",
        ["projects.enum.material.archive_artifact"] = "Архив",
        ["projects.enum.material.multimedia"] = "Мультимедиа",
        ["projects.recovery.execution_state.recovery_hold"] = "Режим восстановления",
        ["projects.recovery.execution_state.task_detected"] = "Контекст задачи обнаружен",
        ["projects.recovery.execution_detail.disabled"] = "Проводка исполнения все еще отключена. Центральная поверхность возвращена только как проверенный shell.",
        ["projects.recovery.execution_detail.task_detected"] = "{0}, но управляющие элементы исполнения намеренно отключены на этапе восстановления.",
        ["projects.recovery.result_state.evidence_available"] = "Подтверждения доступны",
        ["projects.recovery.result_state.none"] = "Результат не загружен",
        ["projects.recovery.result_detail.capsule_exists"] = "Capsule-документ существует и может быть открыт с поверхности исполнения.",
        ["projects.recovery.result_detail.none"] = "Документ capsule/результата пока не материализован.",
        ["projects.list.title"] = "Список проектов",
        ["projects.list.start_here.title"] = "Начало",
        ["projects.list.start_here.body"] = "Режим проектов начинается здесь. Import и New Project остаются явными входными действиями.",
        ["projects.list.start_here.new_project"] = "Новый проект",
        ["projects.list.start_here.import"] = "Импорт",
        ["projects.list.current_project.title"] = "Текущий проект",
        ["projects.list.current_project.open"] = "Открыть проект",
        ["projects.list.summary"] = "Выберите входной блок проекта. Import и New Project остаются отключены в этом срезе.",
        ["projects.list.current_project.details"] = "Вход текущего проекта остается только для чтения в этом срезе.",
        ["projects.list.notes"] = "Этот список пока остается только для чтения.",
        ["projects.home.title"] = "Главная проекта",
        ["projects.home.open_html"] = "Открыть HTML",
        ["projects.home.open_project_doc"] = "Открыть документ проекта",
        ["projects.home.open_work_cycle"] = "Открыть рабочий цикл",
        ["projects.home.overview"] = "Обзор",
        ["projects.home.materials"] = "Материалы",
        ["projects.home.summary"] = "Откройте HTML, проверьте материалы и прочитайте несколько честных строк состояния.",
        ["projects.home.notes"] = "Эта поверхность остается только для чтения в текущем срезе.",
        ["projects.work_cycle.chat.title"] = "Чат",
        ["projects.work_cycle.focus.auto"] = "Авто",
        ["projects.work_cycle.focus.chat"] = "Чат",
        ["projects.work_cycle.focus.execution"] = "Исполнение",
        ["projects.work_cycle.focus.result"] = "Результат",
        ["projects.work_cycle.project.title"] = "Проект",
        ["projects.work_cycle.project.root"] = "Корень проекта",
        ["projects.work_cycle.state.title"] = "Состояние",
        ["projects.work_cycle.enter_work"] = "В работу",
        ["projects.work_cycle.composer.placeholder"] = "Опишите задачу или добавьте уточнение",
        ["projects.work_cycle.composer.send"] = "Отправить",
        ["projects.work_cycle.execution.title"] = "Поверхность исполнения",
        ["projects.work_cycle.execution.state"] = "Состояние исполнения",
        ["projects.work_cycle.validation.title"] = "Проверка",
        ["projects.work_cycle.available_evidence"] = "Доступные подтверждения",
        ["projects.work_cycle.execution.confirm"] = "Подтвердить",
        ["projects.work_cycle.execution.clarify"] = "Уточнить",
        ["projects.work_cycle.execution.return_to_chat"] = "Вернуться в чат",
        ["projects.work_cycle.execution.clarification_placeholder"] = "Опишите, что нужно уточнить",
        ["projects.work_cycle.execution.apply_clarification"] = "Применить уточнение",
        ["projects.work_cycle.execution.cancel_clarification"] = "Отмена",
        ["projects.work_cycle.open_project_doc"] = "Открыть документ проекта",
        ["projects.work_cycle.open_capsule_doc"] = "Открыть capsule-документ",
        ["projects.work_cycle.execution.confirm_stub"] = "Подтвердить",
        ["projects.work_cycle.execution.clarify_stub"] = "Уточнить",
        ["projects.work_cycle.execution.cancel_stub"] = "Пауза/отмена",
        ["projects.work_cycle.result.title"] = "Поверхность результата",
        ["projects.work_cycle.result.state"] = "Состояние результата",
        ["projects.work_cycle.result.accept"] = "Принять",
        ["projects.work_cycle.result.revise"] = "На доработку",
        ["projects.work_cycle.result.reject"] = "Отклонить",
        ["projects.work_cycle.result.withheld"] = "Что было намеренно оставлено выключенным",
        ["projects.work_cycle.result.return_to_execution"] = "Вернуться к исполнению",
        ["projects.work_cycle.phase_prefix"] = "Фаза: ",
        ["projects.work_cycle.chat.summary_note_active"] = "UI обсуждения активно только в discussion-подобных фазах. Core-driven действия остаются ограничены подтвержденными owner paths.",
        ["projects.work_cycle.validation.reason"] = "Проверка договоренности перед запуском исполнения.",
        ["projects.work_cycle.validation.empty"] = "Договоренность еще не сформирована.",
        ["projects.chrome.note.discussion"] = "В этой фазе активно обсуждение. Отправка остается discussion-only, а вход в работу остается отдельным валидированным переходом.",
        ["projects.chrome.note.execution_preflight"] = "Чат остается основным, пока та же постоянная поверхность исполнения открывается в режиме validation/preflight.",
        ["projects.chrome.note.execution"] = "Исполнение является активной поверхностью. Чат остается видимым только как ограниченный замороженный контекст в этом срезе.",
        ["projects.chrome.note.result"] = "Результат является активной поверхностью решения. Исполнение остается видимым как контекст, а чат остается замороженным.",
        ["projects.chrome.note.completed"] = "Состояние завершения показано только как исторический контекст в этом срезе.",
        ["projects.chrome.note.fallback"] = "Discussion и execution остаются ограничены текущими заново подтвержденными owner paths.",
        ["projects.work_cycle.summary"] = "Текущая фаза: {0}. Рабочий цикл следует фазовой видимости, а путь discussion/preflight частично подключен.",
        ["projects.work_cycle.phase.discussion_reopened"] = "Обсуждение / повторное открытие",
        ["projects.work_cycle.phase.discussion_ready"] = "Обсуждение / готово",
        ["projects.work_cycle.phase.discussion_forming"] = "Обсуждение / формируется",
        ["projects.work_cycle.phase.execution_preflight"] = "Исполнение / preflight",
        ["projects.work_cycle.phase.execution_running"] = "Исполнение / выполняется",
        ["projects.work_cycle.phase.execution_qc"] = "Исполнение / QC",
        ["projects.work_cycle.phase.execution_revision"] = "Исполнение / доработка",
        ["projects.work_cycle.phase.execution_interrupted"] = "Исполнение / прервано",
        ["projects.work_cycle.phase.result_revision_requested"] = "Результат / запрошена доработка",
        ["projects.work_cycle.phase.result_ready"] = "Результат / готово",
        ["projects.work_cycle.phase.completed"] = "Завершено",
        ["projects.work_cycle.phase.discussion_idle"] = "Обсуждение / ожидание",
        ["projects.work_cycle.chat_title.discussion"] = "Обсуждение",
        ["projects.work_cycle.chat_title.execution"] = "Замороженный контекст",
        ["projects.work_cycle.chat_title.result"] = "Контекст решения",
        ["projects.work_cycle.chat_title.completed"] = "Исторический контекст",
        ["projects.work_cycle.surface.primary"] = "Основная поверхность",
        ["projects.work_cycle.surface.frozen"] = "Замороженный контекст",
        ["projects.work_cycle.surface.historical"] = "Исторический контекст",
        ["projects.work_cycle.surface.context"] = "Контекст",
        ["projects.work_cycle.surface.hidden"] = "Скрыто",
        ["projects.work_cycle.surface.active"] = "Активная поверхность",
        ["projects.work_cycle.surface.reference"] = "Справочная поверхность",
        ["projects.work_cycle.surface.visible"] = "Видимая поверхность",
        ["projects.work_cycle.chat_summary.discussion"] = "Чат является основной поверхностью в этой фазе. Он формирует намерение и сохраняет видимым обсуждение проекта, не создавая рабочую истину сам по себе.",
        ["projects.work_cycle.chat_summary.execution"] = "Чат остается видимым только как ограниченный контекст, пока исполнение становится активной рабочей поверхностью.",
        ["projects.work_cycle.chat_summary.result"] = "Чат остается видимым как замороженный контекст, пока исполнение/результат несут активную рабочую и решающую поверхность.",
        ["projects.work_cycle.chat_summary.completed"] = "Видимый контекст обсуждения теперь исторический и больше не является активной управляющей поверхностью.",
        ["projects.work_cycle.chat_summary.fallback"] = "Чат остается частью текущего контекста проекта.",
        ["projects.work_cycle.chat_summary_note.discussion"] = "Composer и действия согласования остаются отключены в этом срезе.",
        ["projects.work_cycle.chat_summary_note.execution"] = "Фаза исполнения не должна снова вводить свободный discussion UI как активное управление.",
        ["projects.work_cycle.chat_summary_note.result"] = "Видимость результата не должна подразумевать завершение жизненного цикла.",
        ["projects.work_cycle.chat_summary_note.completed"] = "Состояние завершения не должно молча стирать историю шага.",
        ["projects.work_cycle.execution_summary.hidden"] = "Поверхность исполнения скрыта, пока фазовая машина не дойдет до территории execution/result.",
        ["projects.work_cycle.execution_summary.preflight"] = "Исполнение присутствует как подготовленный shell до начала активной работы.",
        ["projects.work_cycle.execution_summary.running"] = "Исполнение является активной рабочей поверхностью в этой фазе.",
        ["projects.work_cycle.execution_summary.qc"] = "Исполнение остается видимым, пока активен QC-связанный статус.",
        ["projects.work_cycle.execution_summary.revision"] = "Исполнение снова активно, потому что текущая задача находится в цикле доработки.",
        ["projects.work_cycle.execution_summary.interrupted"] = "Исполнение остается видимым как прерванная/деградировавшая рабочая поверхность.",
        ["projects.work_cycle.execution_summary.visible"] = "Поверхность исполнения видима, потому что этого требует текущая фаза.",
        ["projects.work_cycle.execution_detail.preflight"] = "Preflight не должен создавать активную рабочую истину сам по себе. В этом срезе он остается только для чтения.",
        ["projects.work_cycle.execution_detail.running"] = "Контекст задачи: {0}. Живые управляющие элементы остаются отключены.",
        ["projects.work_cycle.execution_detail.qc"] = "QC-соседний контекст исполнения остается только проекцией. {0}",
        ["projects.work_cycle.execution_detail.revision"] = "Видим revision-контекст исполнения. {0}",
        ["projects.work_cycle.execution_detail.interrupted"] = "Прерванное исполнение должно деградировать честно и не должно делать вид, что живой запуск пережил перезапуск.",
        ["projects.work_cycle.execution_detail.fallback"] = "Детали исполнения остаются только для чтения, пока owner paths не будут заново подтверждены.",
        ["projects.work_cycle.execution_evidence.result_visible"] = "Исполнение остается видимым рядом с результатом.",
        ["projects.work_cycle.execution_evidence.context"] = "Подтверждения исполнения остаются доступными как контекст.",
        ["projects.work_cycle.execution_evidence.format"] = "Состояние документов: проект={0}, capsule={1}. {2}",
        ["projects.work_cycle.result_summary.hidden"] = "Поверхность результата скрыта, пока фазовая машина не дойдет до территории result/revision.",
        ["projects.work_cycle.result_summary.ready"] = "Результат теперь является активной поверхностью решения, а исполнение остается видимым как контекст.",
        ["projects.work_cycle.result_summary.revision"] = "Результат остается видимым как ссылка, потому что текущая задача находится в цикле доработки.",
        ["projects.work_cycle.result_summary.visible"] = "Поверхность результата видима, потому что этого требует текущая фаза.",
        ["projects.work_cycle.result_surface.active"] = "Активная поверхность решения",
        ["projects.work_cycle.result_surface.reference"] = "Справочная поверхность решения",
        ["projects.work_cycle.result_surface.visible"] = "Видимая поверхность решения",
        ["projects.work_cycle.result_detail.ready"] = "Результат остается только для чтения в этом срезе. {0}",
        ["projects.work_cycle.result_detail.revision"] = "Доработка сохраняет результат видимым, но decision hooks остаются отключены в этом срезе.",
        ["projects.work_cycle.result_detail.fallback"] = "Детали результата остаются только для чтения, пока owner paths не будут заново подтверждены.",
        ["projects.work_cycle.result_evidence.capsule_present"] = "Capsule/подтверждение результата присутствует.",
        ["projects.work_cycle.result_evidence.capsule_missing"] = "Capsule/подтверждение результата пока не материализовано.",
        ["projects.work_cycle.result_evidence.revision_reference"] = "Результат остается на экране как ссылка для доработки.",
        ["projects.work_cycle.result_evidence.decision_surface"] = "Результат остается поверхностью решения только когда это поддержано фазовой истиной.",
        ["projects.work_cycle.result_metadata.revision"] = "Активна ссылка на доработку.",
        ["projects.work_cycle.result_metadata.ready"] = "Активна проверка решения.",
        ["projects.work_cycle.result_metadata.unavailable"] = "Проверка решения недоступна.",
        ["projects.work_cycle.result_metadata.format"] = "Стадия документа: {0}. {1}",
        ["projects.message.default_revision_reason"] = "Доработка запрошена с поверхности результата.",
        ["projects.message.revision_input_received"] = "Ввод для доработки получен. Исполнитель подготовил новый результат.",
        ["projects.message.revision_log_prepared"] = "Лог доработки подготовлен из типизированного execution runtime.",
        ["projects.message.revision_execution_brief_prepared"] = "Обновленный execution brief подготовлен из типизированного execution runtime.",
        ["projects.message.revision_accepted"] = "QC принял обновленный результат. Поверхность результата снова готова.",
        ["projects.message.agreement_ready"] = "Договоренность выглядит достаточно сильной, чтобы перейти к preflight-проверке.",
        ["projects.message.agreement_ready_with_defaults"] = "Понял. Оформляю это как ограниченный первый проход по наблюдаемым evidence проекта и безопасным умолчаниям; неизвестные детали toolchain или ассетов останутся предупреждениями для execution review.",
        ["projects.message.agreement_refining"] = "Продолжайте уточнять запрос, пока работу нельзя будет проверить без догадок.",
        ["projects.message.agreement_continue"] = "Продолжайте прояснять запрос до старта работы.",
        ["projects.message.preflight_opened"] = "Preflight открыт. Проверка остается активной до старта исполнения.",
        ["projects.message.preflight_confirmed"] = "Preflight подтвержден. Execution runtime запущен.",
        ["projects.message.execution_guard"] = "Ограждение исполнения: {0}",
        ["projects.message.worker_working"] = "Выполняется...",
        ["projects.message.worker_log_prepared"] = "Лог исполнителя подготовлен из типизированного execution runtime.",
        ["projects.message.execution_brief_prepared"] = "Execution brief подготовлен из типизированного execution runtime.",
        ["projects.message.qc_accepted_produced_result"] = "QC принял произведенный результат. Поверхность результата готова к решению.",
        ["projects.message.run_profile_completed"] = "Команда build/run profile завершилась. Поверхность результата готова к ревью.",
        ["projects.message.run_profile_failed_revision"] = "Команда build/run profile завершилась ошибкой или timeout. Revision открыт с process output.",
        ["projects.message.execution_runtime_failed"] = "Execution runtime упал до получения результата: {0}. {1}",
        ["projects.message.qc_decision_accept"] = "Решение QC: ACCEPT. {0}",
        ["projects.message.qc_decision_revise"] = "Решение QC: REVISE. {0}",
        ["projects.message.qc_decision_reject"] = "Решение QC: REJECT. {0}",
        ["projects.message.qc_decision_unavailable"] = "QC-агент недоступен ({0}). Результат не принят; исполнение возвращено в revision или retry.",
        ["projects.message.worker_refused_abandoned"] = "Worker вернул refused/failed. Результат не получен; задача {0} оставлена без ревью QC.",
        ["projects.message.qc_revise_revision_cycle_opened"] = "Решение QC: REVISE. Цикл возвращён в revision; отправьте правки для продолжения.",
        ["projects.message.qc_reject_task_abandoned"] = "Решение QC: REJECT. Задача {0} оставлена; смена остаётся открытой.",
        ["projects.message.staged_summary"] = "Worker заставил {0} файл(ов) в песочницу ({1} применено, {2} пропущено). Корень staging: {3}",
        ["projects.message.staging_applied"] = "В проект применены {0} staged-файл(ов): {1}",
        ["projects.message.staging_hash_drift"] = "Обнаружен hash-дрейф при apply: {0}",
        ["projects.message.accepted_result_apply_blocked"] = "Apply принятого результата заблокирован: {0}",
        ["projects.message.worker_llm_unavailable_fresh"] = "Worker LLM недоступен ({0}). Задача {1} помечена abandoned; staging сохранён для инспекции. Отправь intent ещё раз для retry.",
        ["projects.message.worker_llm_unavailable_revision"] = "Worker LLM недоступен ({0}). Revision-цикл оставлен как есть; staging сохранён. Отправь revision-текст ещё раз для retry.",
        ["projects.message.clarification_requested"] = "Уточнение запрошено до старта исполнения.",
        ["projects.message.clarification_accepted"] = "Уточнение принято. Обновленная договоренность: {0}",
        ["projects.message.returned_to_chat"] = "Возврат в чат. Execution runtime не был запущен.",
        ["projects.message.interrupted_returned_to_chat"] = "Возврат в чат из прерванного исполнения. Результат не применялся.",
        ["projects.message.accepted_result_applied"] = "Принятый результат применен. Коммит записан как {0}.",
        ["projects.message.revision_requested"] = "Запрошена доработка. Исполнение возвращено в цикл revision.",
        ["projects.message.result_rejected"] = "Результат отклонен. Задача {0} была оставлена, смена остается открытой.",
        ["projects.message.agreement_not_formed"] = "- Договоренность еще не сформирована.",
        ["projects.message.recovered_task_from_validation"] = "Восстановленная задача из UI-проверки.",
        ["projects.message.acceptance.project"] = "Подготовить подтвержденный результат для проекта '{0}'.",
        ["projects.message.acceptance.qc"] = "Решение QC должно быть принято до apply или reject.",
        ["projects.message.acceptance.document_stage"] = "Соблюдать текущую стадию документа '{0}'.",
        ["projects.message.worker_artifact.heading"] = "# Краткий отчет по исполнению",
        ["projects.message.worker_artifact.project"] = "Проект: {0}",
        ["projects.message.worker_artifact.root"] = "Корень: {0}",
        ["projects.message.worker_artifact.task"] = "Задача: {0}",
        ["projects.message.worker_artifact.task_description"] = "Описание задачи: {0}",
        ["projects.message.worker_artifact.runtime_state"] = "Состояние runtime: {0}",
        ["projects.message.worker_artifact.qc_status"] = "Статус QC: {0}",
        ["projects.message.worker_artifact.result"] = "## Результат",
        ["projects.message.worker_artifact.advisory"] = "## Подсказки",
        // ── Projects Web UI (prototype, RU) ────────────────────────────────
        ["projects.title"] = "ZAVOD · Проекты",
        ["projects.phase.list"] = "список",
        ["projects.phase.home"] = "главная",
        ["projects.phase.workCycle"] = "рабочий цикл",
        ["projects.list.import"] = "Импортировать проект",
        ["projects.list.new"] = "Новый проект",
        ["projects.status.active"] = "в работе",
        ["projects.status.review"] = "review",
        ["projects.status.idle"] = "ожидает",
        ["projects.nav.toList"] = "проекты",
        ["projects.nav.toHome"] = "главная",
        ["projects.stats.files"] = "файлов",
        ["projects.stats.anchors"] = "фактов найдено",
        ["projects.stats.tasks"] = "задач",
        ["projects.stats.docs"] = "документов",
        ["projects.home.currentLabel"] = "текущий проект",
        ["projects.home.enterWork"] = "войти в рабочий цикл",
        ["projects.home.scannerAnalysis"] = "анализ сканера",
        ["projects.home.truthDocs"] = "документы истины",
        ["projects.home.nextActions"] = "следующие действия",
        ["projects.home.missingTruth"] = "чего не хватает",
        ["projects.home.userDocs"] = "пользовательские документы",
        ["projects.welcome.action.review_preview_docs"] = "проверить превью",
        ["projects.welcome.action.promote_preview_to_canonical"] = "принять в канон",
        ["projects.welcome.action.author_canonical_doc"] = "написать документ",
        ["projects.welcome.action.start_work_cycle"] = "начать работу",
        ["projects.welcome.action.continue_work_cycle"] = "продолжить работу",
        ["projects.welcome.action.review_project_audit"] = "проверить аудит",
        ["projects.welcome.action.review_stale_sections"] = "проверить устаревшее",
        ["projects.welcome.action.import_retry"] = "повторить импорт",
        ["projects.welcome.action.reject_preview"] = "отклонить превью",
        ["projects.welcome.action.open_roadmap"] = "открыть roadmap",
        ["projects.welcome.action.open_direction"] = "открыть direction",
        ["projects.welcome.detail.review_preview_docs"] = "Откройте блок документов и проверьте кандидатную истину.",
        ["projects.welcome.detail.promote_preview_to_canonical"] = "Используйте кнопки принятия у проверенных preview-документов.",
        ["projects.welcome.detail.author_canonical_doc"] = "Ручное создание документа еще не подключено в этой сборке.",
        ["projects.welcome.detail.start_work_cycle"] = "Откройте рабочий цикл и опишите первую задачу.",
        ["projects.welcome.detail.continue_work_cycle"] = "Вернитесь к активной рабочей поверхности проекта.",
        ["projects.welcome.detail.review_project_audit"] = "Откройте отчет сканера и импортный аудит проекта.",
        ["projects.welcome.detail.review_stale_sections"] = "Проверка устаревших секций еще не подключена в этой сборке.",
        ["projects.welcome.detail.import_retry"] = "Запустите импорт проекта для этой рабочей папки еще раз.",
        ["projects.welcome.detail.reject_preview"] = "Используйте кнопки отклонения у preview-документов.",
        ["projects.welcome.detail.open_roadmap"] = "Roadmap-поверхность еще не подключена в этой сборке.",
        ["projects.welcome.detail.open_direction"] = "Direction-поверхность еще не подключена в этой сборке.",
        ["projects.report.label"] = "отчёт сканера",
        ["projects.report.open"] = "открыть",
        ["projects.report.modal.label"] = "отчёт сканера",
        ["projects.report.modal.close"] = "закрыть ✕",
        ["projects.anchor.tag.file"] = "файл",
        ["projects.anchor.tag.problem"] = "проблема",
        ["projects.anchor.tag.dependency"] = "зависимость",
        ["projects.anchor.conf.confirmed"] = "точно",
        ["projects.anchor.conf.likely"] = "вероятно",
        ["projects.docs.category.text"] = "markdown · txt",
        ["projects.docs.category.pdf"] = "pdf",
        ["projects.docs.category.html"] = "html",
        ["projects.docs.promote"] = "в канон",
        ["projects.docs.reject"] = "отклонить",
        ["projects.docs.canonical"] = "канон",
        ["projects.docs.absent"] = "нет",
        ["projects.composer.placeholder"] = "Опишите задачу...",
        ["projects.composer.intent"] = "в работу",
        ["projects.composer.intent.kbd"] = "tab",
        ["projects.preflight.kicker"] = "План выполнения",
        ["projects.preflight.title"] = "Preflight",
        ["projects.preflight.confirm"] = "Запустить",
        ["projects.preflight.clarify"] = "Уточнить",
        ["projects.preflight.back"] = "Назад",
        ["projects.preflight.clarify.label"] = "уточнение",
        ["projects.preflight.clarify.placeholder"] = "что нужно скорректировать...",
        ["projects.preflight.clarify.send"] = "отправить ↑",
        ["projects.worker.label"] = "worker",
        ["projects.artifact.code"] = "код",
        ["projects.artifact.preview"] = "превью",
        ["projects.artifact.waiting"] = "ожидание изменений...",
        ["projects.artifact.refresh"] = "обновить",
        ["projects.artifact.share"] = "поделиться",
        ["projects.action.tasks"] = "задач",
        ["projects.action.files"] = "файлов",
        ["projects.action.errors"] = "ошибок",
        ["projects.action.revise.placeholder"] = "что доработать...",
        ["projects.action.revise.send"] = "отправить ↑",
        ["projects.action.revise"] = "На доработку",
        ["projects.action.reject"] = "Отклонить",
        ["projects.action.confirm"] = "Подтвердить",
        // ── New project modal (RU) ────────────────────────────────────────
        ["projects.newProject.title"] = "Новый проект",
        ["projects.newProject.nameLabel"] = "Название",
        ["projects.newProject.namePlaceholder"] = "Мой новый проект",
        ["projects.newProject.kindLabel"] = "Что это (примерно)",
        ["projects.newProject.pathLabel"] = "Будет создан в",
        ["projects.newProject.pathHint"] = "Имя папки фиксируется при создании. Название проекта можно менять потом.",
        ["projects.newProject.cancel"] = "Отмена",
        ["projects.newProject.create"] = "Создать",
        ["projects.kind.generic"] = "Прочее",
        ["projects.kind.webFrontend"] = "Веб-приложение (фронтенд)",
        ["projects.kind.webBackend"] = "Бэкенд-сервис",
        ["projects.kind.game"] = "Игра",
        ["projects.kind.library"] = "Библиотека / SDK",
        ["projects.kind.mobile"] = "Мобильное приложение",
        ["projects.kind.cli"] = "CLI-утилита",
        ["projects.kind.docs"] = "Документация"
    });
}
